# Generated by Django 3.2 on 2021-04-28 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0003_alter_shop_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shop',
            options={'ordering': ('state',)},
        ),
        migrations.AddField(
            model_name='shop',
            name='resources',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='shop',
            name='special_remarks',
            field=models.CharField(default='', max_length=200),
        ),
    ]
