# Generated by Django 3.2 on 2021-05-06 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0004_auto_20210428_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
