# Generated by Django 3.2.2 on 2021-05-06 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0005_shop_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='shop',
            name='state',
            field=models.CharField(default='', max_length=100),
        ),
    ]
