# Generated by Django 3.2.2 on 2021-05-08 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0006_auto_20210506_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='verified_at',
            field=models.CharField(default='', max_length=100),
        ),
    ]
